xcopy ..\Release\Client.exe ..\..\Bin /y 
xcopy ..\Release\Client.pdb ..\..\Bin /y 
xcopy ..\Release\RenderProxy.exe ..\..\Bin /y 
xcopy ..\Release\RenderProxy.pdb ..\..\Bin /y 
xcopy ..\Release\GameLoader.exe ..\..\Bin /y 
xcopy ..\Release\GameLoader.pdb ..\..\Bin /y 
xcopy ..\Release\DisManager.exe ..\..\Bin /y 
xcopy ..\Release\DisManager.pdb ..\..\Bin /y 
xcopy ..\Release\LogicServer.dll ..\..\Bin /y 
xcopy ..\Release\LogicServer.pdb ..\..\Bin /y 