xcopy ..\Debug\Client.exe ..\..\Bin /y 
xcopy ..\Debug\Client.pdb ..\..\Bin /y 
xcopy ..\Debug\RenderProxy.exe ..\..\Bin /y 
xcopy ..\Debug\RenderProxy.pdb ..\..\Bin /y 
xcopy ..\Debug\GameLoader.exe ..\..\Bin /y 
xcopy ..\Debug\GameLoader.pdb ..\..\Bin /y 
xcopy ..\Debug\DisManager.exe ..\..\Bin /y 
xcopy ..\Debug\DisManager.pdb ..\..\Bin /y 
xcopy ..\Debug\LogicServer.dll ..\..\Bin /y 
xcopy ..\Debug\LogicServer.pdb ..\..\Bin /y 